
<!--
    ╔═══════════════════════════════════════════════════════════════════════════╗
    ║   This code was created by AI, not by me :)                               ║
    ║                                                                           ║
    ║   This entire HTML page was created using Artificial Intelligence         ║
    ║   Generated by: Claude (Anthropic)                                        ║                                             ║
    ╚═══════════════════════════════════════════════════════════════════════════╝
-->

<?php
session_start();
include '../.gitignore/db.php';

// check if user is logged in
if (!isset($_SESSION['admin_id'])) {
    header("Location: login.php");
    exit();
}

$staff_name = $_SESSION['staff_name'];
$staff_role = $_SESSION['staff_role'];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard - Qudus</title>
    <link href="https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=Cairo:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">
    <style>
        :root {
            --navy: #192938;
            --gold: #d18a0f;
            --gold-hover: #a7762a;
            --ivory: #F2F0E6;
            --bg-dark: #080d18;
            --card-bg: #1c232b;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Cairo', sans-serif;
            background: linear-gradient(135deg, #080d18 0%, #0f1921 50%, #080d18 100%);
            color: var(--ivory);
            line-height: 1.6;
            min-height: 100vh;
            position: relative;
        }

        body::before {
            content: '';
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-image: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M30 0l2 2-2 2-2-2 2-2zm0 56l2 2-2 2-2-2 2-2zM0 30l2 2-2 2-2-2 2-2zm56 0l2 2-2 2-2-2 2-2z' fill='%23d18a0f' fill-opacity='0.03'/%3E%3C/svg%3E");
            opacity: 0.4;
            pointer-events: none;
            z-index: 0;
        }

        .navbar {
            position: fixed;
            display: flex;
            justify-content: space-between;
            align-items: center;
            width: 100%;
            padding: 1rem 3rem;
            background-color: #020d18a7;
            backdrop-filter: blur(10px);
            z-index: 1000;
            top: 0;
        }

        .navbar-left {
            display: flex;
            align-items: center;
            gap: 1rem;
        }

        .logo-text {
            font-size: 1.5rem;
            font-weight: bold;
            color: #b9812d;
            font-family: 'Amiri', serif;
        }

        .welcome-text {
            color: rgba(242, 240, 230, 0.8);
            font-size: 0.95rem;
        }

        .welcome-text strong {
            color: var(--gold);
        }

        .logout-btn {
            background-color: rgba(244, 67, 54, 0.2);
            color: #FF6B6B;
            border: 1px solid rgba(244, 67, 54, 0.5);
            padding: 0.6rem 1.5rem;
            border-radius: 0.5rem;
            cursor: pointer;
            font-weight: 600;
            font-size: 0.9rem;
            font-family: 'Cairo', sans-serif;
            transition: all 0.3s;
            text-decoration: none;
            display: inline-block;
        }

        .logout-btn:hover {
            background-color: rgba(244, 67, 54, 0.3);
            transform: translateY(-2px);
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 8rem 2rem 4rem;
            position: relative;
            z-index: 1;
        }

        .page-header {
            text-align: center;
            margin-bottom: 3rem;
        }

        .page-title {
            font-family: 'Amiri', serif;
            font-size: 3rem;
            color: var(--gold);
            margin-bottom: 0.5rem;
            letter-spacing: 1px;
        }

        .page-subtitle {
            color: rgba(242, 240, 230, 0.6);
            font-size: 1.1rem;
            font-weight: 300;
        }

        .dashboard-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 2rem;
            margin-top: 3rem;
        }

        .dashboard-card {
            background: linear-gradient(145deg, rgba(28, 35, 43, 0.95), rgba(25, 41, 56, 0.85));
            border-radius: 0.8rem;
            border: 1px solid rgba(212, 175, 55, 0.15);
            padding: 2.5rem;
            transition: all 0.4s ease;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
            backdrop-filter: blur(10px);
            position: relative;
            overflow: hidden;
            text-align: center;
        }

        .dashboard-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 4px;
            background: linear-gradient(90deg, var(--gold), transparent);
            opacity: 0;
            transition: opacity 0.4s ease;
        }

        .dashboard-card:hover {
            transform: translateY(-5px);
            border-color: rgba(212, 175, 55, 0.4);
            box-shadow: 0 8px 30px rgba(212, 175, 55, 0.2);
        }

        .dashboard-card:hover::before {
            opacity: 1;
        }

        .card-icon {
            font-size: 3.5rem;
            color: var(--gold);
            margin-bottom: 1rem;
        }

        .card-title {
            font-family: 'Amiri', serif;
            font-size: 1.8rem;
            color: var(--ivory);
            margin-bottom: 1rem;
        }

        .card-desc {
            color: rgba(242, 240, 230, 0.6);
            font-size: 0.95rem;
            margin-bottom: 2rem;
            line-height: 1.6;
        }

        .card-actions {
            display: flex;
            gap: 0.8rem;
            justify-content: center;
            flex-wrap: wrap;
        }

        .action-btn {
            padding: 0.7rem 1.5rem;
            border-radius: 0.5rem;
            font-size: 0.9rem;
            font-weight: 600;
            cursor: pointer;
            font-family: 'Cairo', sans-serif;
            transition: all 0.3s ease;
            text-decoration: none;
            display: inline-block;
            border: none;
        }

        .btn-add {
            background: linear-gradient(135deg, var(--gold) 0%, #c59321 100%);
            color: var(--navy);
            box-shadow: 0 2px 10px rgba(212, 175, 55, 0.3);
        }

        .btn-add:hover {
            background: linear-gradient(135deg, #c59321 0%, var(--gold) 100%);
            transform: translateY(-2px);
            box-shadow: 0 4px 15px rgba(212, 175, 55, 0.4);
        }

        .btn-view {
            background-color: rgba(33, 150, 243, 0.2);
            color: #64B5F6;
            border: 1px solid rgba(33, 150, 243, 0.3);
        }

        .btn-view:hover {
            background-color: rgba(33, 150, 243, 0.3);
            transform: translateY(-2px);
        }

        @media (max-width: 768px) {
            .navbar {
                flex-direction: column;
                gap: 1rem;
                padding: 1rem;
            }

            .container {
                padding: 12rem 1.5rem 3rem;
            }

            .page-title {
                font-size: 2.2rem;
            }

            .dashboard-grid {
                grid-template-columns: 1fr;
                gap: 1.5rem;
            }
        }
    </style>
</head>
<body>
    <nav class="navbar">
        <div class="navbar-left">
            <span class="logo-text">Qudus Admin</span>
            <span class="welcome-text">Welcome, <strong><?= htmlspecialchars($staff_name) ?></strong> (<?= htmlspecialchars($staff_role) ?>)</span>
        </div>
        <a href="logout.php" class="logout-btn">Logout</a>
    </nav>

    <div class="container">
        <div class="page-header">
            <h1 class="page-title">Dashboard</h1>
            <p class="page-subtitle">Manage your museum content and operations</p>
        </div>

        <div class="dashboard-grid">
            <!-- Exhibitions Card -->
            <div class="dashboard-card">
                <div class="card-icon">🏛️</div>
                <h2 class="card-title">Exhibitions</h2>
                <p class="card-desc">Manage current, upcoming, and past exhibitions</p>
                <div class="card-actions">
                    <a href="manage_exhibitions.php?action=add" class="action-btn btn-add">Add New</a>
                    <a href="manage_exhibitions.php" class="action-btn btn-view">View All</a>
                </div>
            </div>

            <!-- Orders Card -->
            <div class="dashboard-card">
                <div class="card-icon">📦</div>
                <h2 class="card-title">Orders</h2>
                <p class="card-desc">View and manage 3D print orders from customers</p>
                <div class="card-actions">
                    <a href="manage_orders.php" class="action-btn btn-view">View All</a>
                </div>
            </div>

            <!-- Collections Card -->
            <div class="dashboard-card">
                <div class="card-icon">🏺</div>
                <h2 class="card-title">Collections</h2>
                <p class="card-desc">Manage museum artifacts and historical pieces</p>
                <div class="card-actions">
                    <a href="manage_collections.php?action=add" class="action-btn btn-add">Add New</a>
                    <a href="manage_collections.php" class="action-btn btn-view">View All</a>
                </div>
            </div>

            <!-- Artworks Card -->
            <div class="dashboard-card">
                <div class="card-icon">🎨</div>
                <h2 class="card-title">Artworks</h2>
                <p class="card-desc">Manage artwork pieces and cultural treasures</p>
                <div class="card-actions">
                    <a href="manage_artworks.php?action=add" class="action-btn btn-add">Add New</a>
                    <a href="manage_artworks.php" class="action-btn btn-view">View All</a>
                </div>
            </div>

            <!-- Visits Card -->
            <div class="dashboard-card">
                <div class="card-icon">👥</div>
                <h2 class="card-title">Visits</h2>
                <p class="card-desc">View registered visitors and their bookings</p>
                <div class="card-actions">
                    <a href="manage_visits.php" class="action-btn btn-view">View All</a>
                </div>
            </div>

            <!-- Visitors Card -->
            <div class="dashboard-card">
                <div class="card-icon">📋</div>
                <h2 class="card-title">Visitors</h2>
                <p class="card-desc">Manage visitor information and contact details</p>
                <div class="card-actions">
                    <a href="manage_visitors.php" class="action-btn btn-view">View All</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>